// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulofjjawfebwgtukwduw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsb2ZqamF3ZmVid2d0dWt3ZHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDIyMDksImV4cCI6MjA3Mjk3ODIwOX0.kJbAJ1IJOVrlbwjEupaCsUNR5dHumiZBrBshLnZh7E4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});